"""Initial migration

Revision ID: 1a2b3c4d5e6f
Revises: 
Create Date: 2026-05-03 12:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('password', sa.String(length=100), nullable=False),
        sa.Column('role', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edit_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('inputVideo', sa.String(length=255), nullable=False),
        sa.Column('outputVideo', sa.String(length=255), nullable=True),
        sa.Column('subtitle', sa.String(length=255), nullable=False),
        sa.Column('time', sa.String(length=100), nullable=True),
        sa.Column('model_key', sa.String(length=50), nullable=True),
        sa.Column('analysis_time', sa.Float(), nullable=True),
        sa.Column('highlights_found', sa.Integer(), nullable=True),
        sa.Column('avg_confidence', sa.Float(), nullable=True),
        sa.Column('model_load_time', sa.Float(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('segment', sa.String(length=255), nullable=False),
        sa.Column('video', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segments')
    op.drop_table('edit_history')
    op.drop_table('users')
    # ### end Alembic commands ###
